import { spawn, spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const WORKER_ROOT = path.resolve(__dirname, "..");
const PLAYWRIGHT_IMAGE = process.env.PLAYWRIGHT_IMAGE || "mcr.microsoft.com/playwright:v1.55.0-jammy";

export function toDockerPath(inputPath) {
  const resolved = path.resolve(inputPath);
  if (process.platform === "win32") {
    return resolved.replace(/\\/g, "/");
  }
  return resolved;
}

let dockerOk = null;

export function dockerAvailable() {
  if (dockerOk !== null) {
    return dockerOk;
  }
  try {
    const probe = spawnSync(findDockerBin(), ["info"], {
      timeout: 8000,
      windowsHide: true,
      stdio: "ignore",
    });
    dockerOk = probe.status === 0;
  } catch {
    dockerOk = false;
  }
  return dockerOk;
}

function findDockerBin() {
  const fromEnv = process.env.DOCKER_BIN;
  if (fromEnv && fs.existsSync(fromEnv)) {
    return fromEnv;
  }
  return process.platform === "win32" ? "docker.exe" : "docker";
}

function writePlaywrightConfig(configPath, { testDir, outputDir, reportPath, timeoutMs, hasStorageState }) {
  const storageLine = hasStorageState ? "storageState: process.env.STORAGE_STATE," : "";
  const contents = `// Generated by TestFlow Node worker — do not edit
module.exports = {
  testDir: ${JSON.stringify(testDir)},
  outputDir: ${JSON.stringify(outputDir)},
  timeout: ${timeoutMs},
  fullyParallel: false,
  workers: 1,
  reporter: [['list'], ['json', { outputFile: ${JSON.stringify(reportPath)} }]],
  use: {
    ${storageLine}
    screenshot: 'only-on-failure',
    trace: 'retain-on-failure',
    video: 'retain-on-failure',
  },
};
`;
  fs.mkdirSync(path.dirname(configPath), { recursive: true });
  fs.writeFileSync(configPath, contents, "utf8");
}

function collectArtifacts(artifactsDir, projectRootHint) {
  if (!fs.existsSync(artifactsDir)) {
    return [];
  }
  const files = [];
  const walk = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(full);
      } else if (entry.isFile()) {
        files.push(full.replace(/\\/g, "/"));
      }
    }
  };
  walk(artifactsDir);
  return files;
}

async function runCommand(command, args, { timeoutMs, env, cwd } = {}) {
  return new Promise((resolve) => {
    const child = spawn(command, args, {
      env: env || process.env,
      cwd,
      windowsHide: true,
    });
    let stdout = "";
    let stderr = "";
    let settled = false;

    const finish = (exitCode, errorMessage) => {
      if (settled) {
        return;
      }
      settled = true;
      resolve({ exitCode, stdout, stderr, errorMessage });
    };

    child.stdout?.on("data", (chunk) => {
      stdout += chunk.toString();
    });
    child.stderr?.on("data", (chunk) => {
      stderr += chunk.toString();
    });
    child.on("error", (err) => {
      finish(1, err.message);
    });
    child.on("close", (code) => {
      finish(code ?? 1, null);
    });

    if (timeoutMs && timeoutMs > 0) {
      setTimeout(() => {
        if (settled) {
          return;
        }
        try {
          child.kill("SIGKILL");
        } catch {
          // ignore
        }
        finish(124, `Execution timed out after ${Math.round(timeoutMs / 1000)} seconds`);
      }, timeoutMs).unref?.();
    }
  });
}

export async function executeTest({
  testFile,
  executionId,
  artifactsDir,
  authStorageStatePath,
  timeoutSeconds = 60,
  executionMode = "auto",
}) {
  const started = Date.now();
  const artifactsAbs = path.resolve(artifactsDir);
  const logsDir = path.join(artifactsAbs, "logs");
  const playwrightOut = path.join(artifactsAbs, "playwright");
  fs.mkdirSync(logsDir, { recursive: true });
  fs.mkdirSync(playwrightOut, { recursive: true });

  const stdoutLog = path.join(logsDir, "stdout.log");
  const stderrLog = path.join(logsDir, "stderr.log");
  const reportPath = path.join(artifactsAbs, "playwright-report.json");
  const configPath = path.join(artifactsAbs, "playwright.config.cjs");

  const testFileAbs = path.resolve(testFile);
  const testDirAbs = path.dirname(testFileAbs);
  const timeoutMs = timeoutSeconds * 1000;
  const hasStorageState = Boolean(authStorageStatePath && fs.existsSync(authStorageStatePath));
  const preferDocker = executionMode !== "local";
  const useDocker = preferDocker && dockerAvailable();

  let telemetry;
  if (useDocker) {
    writePlaywrightConfig(configPath, {
      testDir: "/work/tests",
      outputDir: "/work/artifacts/playwright",
      reportPath: "/work/artifacts/playwright-report.json",
      timeoutMs,
      hasStorageState,
    });
    telemetry = await runInDocker({
      executionId,
      testDirAbs,
      artifactsAbs,
      configPath,
      authStorageStatePath: hasStorageState ? authStorageStatePath : null,
      timeoutMs,
    });
  } else {
    writePlaywrightConfig(configPath, {
      testDir: testDirAbs,
      outputDir: playwrightOut,
      reportPath,
      timeoutMs,
      hasStorageState,
    });
    telemetry = await runLocal({
      testFileAbs,
      configPath,
      artifactsAbs,
      authStorageStatePath: hasStorageState ? authStorageStatePath : null,
      timeoutMs,
    });
  }

  const duration = Number(((Date.now() - started) / 1000).toFixed(3));
  fs.writeFileSync(stdoutLog, telemetry.stdout || "", "utf8");
  fs.writeFileSync(stderrLog, telemetry.stderr || "", "utf8");

  return {
    exit_code: telemetry.exitCode,
    duration,
    stdout: telemetry.stdout,
    stderr: telemetry.stderr,
    error_message: telemetry.errorMessage,
    artifacts: collectArtifacts(artifactsAbs),
    runner_type: useDocker ? "docker" : "local_fallback",
    log_file: stdoutLog.replace(/\\/g, "/"),
  };
}

async function runInDocker({
  executionId,
  testDirAbs,
  artifactsAbs,
  configPath,
  authStorageStatePath,
  timeoutMs,
}) {
  const containerName = `testflow-exec-${executionId}`;
  const docker = findDockerBin();
  const args = [
    "run",
    "--rm",
    "--name",
    containerName,
    "-v",
    `${toDockerPath(testDirAbs)}:/work/tests:ro`,
    "-v",
    `${toDockerPath(artifactsAbs)}:/work/artifacts`,
    "-v",
    `${toDockerPath(configPath)}:/work/playwright.config.cjs:ro`,
    "-v",
    `${toDockerPath(WORKER_ROOT)}:/opt/testflow-worker:ro`,
    "-v",
    `${toDockerPath(path.join(WORKER_ROOT, "node_modules"))}:/work/node_modules:ro`,
    "-e",
    `EXECUTION_ID=${executionId}`,
    "-w",
    "/work",
    "--ipc=host",
  ];

  if (process.env.TESTFLOW_BASE_URL) {
    args.push("-e", `TESTFLOW_BASE_URL=${process.env.TESTFLOW_BASE_URL}`);
  }

  if (authStorageStatePath) {
    args.push(
      "-v",
      `${toDockerPath(authStorageStatePath)}:/work/auth_state.json:ro`,
      "-e",
      "STORAGE_STATE=/work/auth_state.json",
    );
  }

  args.push(
    PLAYWRIGHT_IMAGE,
    "node",
    "/opt/testflow-worker/node_modules/@playwright/test/cli.js",
    "test",
    "--config=/work/playwright.config.cjs",
  );

  const result = await runCommand(docker, args, { timeoutMs });
  if (result.exitCode === 124) {
    await runCommand(docker, ["kill", containerName], { timeoutMs: 10_000 });
    return {
      exitCode: 124,
      stdout: result.stdout,
      stderr: result.stderr || `Execution timed out after ${Math.round(timeoutMs / 1000)} seconds.`,
      errorMessage: "Execution timed out in Docker container",
    };
  }
  return {
    exitCode: result.exitCode,
    stdout: result.stdout,
    stderr: result.stderr,
    errorMessage: result.errorMessage || (result.exitCode === 0 ? null : extractError(result.stdout, result.stderr, result.exitCode)),
  };
}

async function runLocal({
  testFileAbs,
  configPath,
  artifactsAbs,
  authStorageStatePath,
  timeoutMs,
}) {
  const env = {
    ...process.env,
    EXECUTION_ID: process.env.EXECUTION_ID,
    TESTFLOW_ARTIFACTS_DIR: artifactsAbs,
  };
  if (authStorageStatePath) {
    env.STORAGE_STATE = authStorageStatePath;
  }

  const specFilter = path.relative(path.dirname(testFileAbs), testFileAbs) || path.basename(testFileAbs);
  const playwrightCli = path.join(WORKER_ROOT, "node_modules", "@playwright", "test", "cli.js");
  const result = await runCommand(
    process.execPath,
    [playwrightCli, "test", specFilter, `--config=${configPath}`],
    {
      timeoutMs,
      env,
      cwd: path.dirname(testFileAbs),
    },
  );

  return {
    exitCode: result.exitCode,
    stdout: result.stdout,
    stderr: result.stderr,
    errorMessage:
      result.exitCode === 124
        ? result.errorMessage
        : result.errorMessage || (result.exitCode === 0 ? null : extractError(result.stdout, result.stderr, result.exitCode)),
  };
}

function extractError(stdout, stderr, exitCode) {
  const combined = `${stdout}\n${stderr}`;
  const lines = combined.split(/\r?\n/).filter((line) => /failed|error|timeout/i.test(line));
  return lines.at(-1) || `Test exited with non-zero status code: ${exitCode}`;
}
