"use client";

import { Play, Sparkles } from "lucide-react";
import { Link, useParams } from "@/lib/navigation";
import { suites, testCases } from "@/lib/demoData";
import { StatusBadge } from "@/components/common/StatusBadge";
export function TestSuiteDetailPage(){const {id='demo-project',suiteId='admissions'}=useParams();const suite=suites.find(s=>s.id===suiteId)||suites[0];const rows=testCases.slice(0,6);return <div className="p-6 lg:p-8"><div className="rounded-lg border border-indigo-200 bg-indigo-50 p-4"><div className="flex items-center justify-between"><span className="font-semibold"><Sparkles size={16} className="mr-2 inline text-indigo-600"/>3 suite suggestions are ready for review</span><Link to={`/projects/${id}/suites/review`} className="rounded-lg-lg bg-indigo-600 px-3 py-2 text-sm text-white">Review Suggestions 3</Link></div></div><div className="mt-6 flex flex-wrap items-start justify-between gap-4"><div><Link to={`/projects/${id}/suites`} className="text-sm text-indigo-600">← Test Suites</Link><h1 className="mt-2 text-3xl font-bold">{suite.name}</h1><p className="mt-1 text-sm text-slate-500">{suite.description}</p></div><Link to={`/projects/${id}/runs/104/live`} className="rounded-lg-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white"><Play size={15} className="mr-1 inline"/>Run Suite</Link></div><div className="mt-6 overflow-hidden rounded-lg bg-white shadow-sm"><table className="w-full text-sm"><thead className="bg-indigo-50 text-xs uppercase text-slate-600"><tr><th className="px-5 py-3 text-left">Test Case</th><th className="px-5 py-3 text-left">Automation</th><th className="px-5 py-3 text-left">Status</th><th className="px-5 py-3 text-left">Last Run</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody>{rows.map(t=><tr key={t.id} className="border-t"><td className="px-5 py-4"><span className="mr-2 rounded-lg bg-slate-100 px-2 py-1 font-mono text-xs">{t.id}</span><span className="font-medium">{t.name}</span></td><td className="px-5 text-slate-600">{t.automation}</td><td className="px-5"><StatusBadge status={t.status}/></td><td className="px-5 text-slate-500">{t.lastRun}</td><td className="px-5 text-right"><Link to={`/projects/${id}/test-cases/${t.id}`} className="text-indigo-600">Open</Link></td></tr>)}</tbody></table></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[['TEST CASES',suite.cases],['PASSED',suite.passed],['FAILED',suite.failed],['PASS RATE',`${suite.passRate}%`],['LAST RUN',suite.lastRun]].map(([a,b])=><div key={String(a)} className="rounded-lg bg-white p-4 shadow-sm"><p className="text-xs text-slate-500">{a}</p><p className="mt-2 text-2xl font-bold">{b}</p></div>)}</div></div>}

export default TestSuiteDetailPage;
